version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root2001
      MYSQL_DATABASE: products
      MYSQL_USER: root
      MYSQL_PASSWORD: root2001
    ports:
      - "3308:3306"  # Host:Container
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - order-network

  order-service:
    build: .
    container_name: order-service
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/products
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root2001
    ports:
      - "8080:8080"
    networks:
      - order-network

volumes:
  mysql_data:

networks:
  order-network:
