spring:
  application:
    name: welcome-api-service  
  boot:
    admin:
      client:
        url: http://localhost:1111/
        instance:
          prefer-ip: true  
          service-base-url: http://localhost:8081  
          
    zipkin:
      base-url: http://localhost:9411
      enabled: true
    sleuth:
      sampler:
      probability: 1.0        
server:
  port: 8081 
management:
  endpoints:
    web:
      exposure:
        include: '*' 
        

                  